22/11/2022 16:52:32: error: uncaughtException: Illegal arguments: undefined, string
Error: Illegal arguments: undefined, string
    at Object.bcrypt.compareSync (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/bcryptjs/dist/bcrypt.js:265:19)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:24:35
    at step (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:33:23)
    at Object.next (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:14:53)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:4:12)
    at Query.<anonymous> (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:15:88)
    at Query.handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/client.js:290:19)
22/11/2022 16:53:33: error: uncaughtException: Illegal arguments: undefined, string
Error: Illegal arguments: undefined, string
    at Object.bcrypt.compareSync (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/bcryptjs/dist/bcrypt.js:265:19)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:24:35
    at step (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:33:23)
    at Object.next (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:14:53)
    at /home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:4:12)
    at Query.<anonymous> (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/src/services/loginService.ts:15:88)
    at Query.handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/home/carlos/workspace/simple-tasks-api/simple-tasks-backend/node_modules/pg/lib/client.js:290:19)
06/08/2023 19:11:06: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:51:17
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:14:57: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:15:31: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:16:19: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:17:28: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:145:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:18:50: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:143:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:20:44: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:144:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:22:37: error: uncaughtException: current transaction is aborted, commands ignored until end of transaction block
error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/carlos/workspace/simple-tasks-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
06/08/2023 19:23:36: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:144:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
06/08/2023 19:25:27: error: uncaughtException: relation "migrations" does not exist
Error: relation "migrations" does not exist
    at /home/carlos/workspace/simple-tasks-backend/src/migrations/index.ts:148:13
    at step (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/carlos/workspace/simple-tasks-backend/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
07/08/2023 13:22:06: error: uncaughtException: getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at /home/carlos/workspace/simple-tasks-backend/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
07/08/2023 13:22:06: error: uncaughtException: getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at /home/carlos/workspace/simple-tasks-backend/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:02:42: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:02:42: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:03:50: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
09/08/2023 20:03:50: error: uncaughtException: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:10:01: error: uncaughtException: getaddrinfo EAI_AGAIN backend
Error: getaddrinfo EAI_AGAIN backend
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:11:14: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:11:14: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:12:51: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
14/08/2023 12:12:51: error: uncaughtException: no PostgreSQL user name specified in startup packet
error: no PostgreSQL user name specified in startup packet
    at /app/node_modules/pg-pool/index.js:45:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
23/08/2023 22:45:57: error: uncaughtException: terminating connection due to administrator command
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Socket.Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
16/10/2023 11:56:22: error: uncaughtException: migration is not a function
Error: migration is not a function
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
20/10/2023 12:02:59: error: uncaughtException: Cannot read properties of undefined (reading 'user_id')
TypeError: Cannot read properties of undefined (reading 'user_id')
    at parseUserToSend (/app/src/utils/commonFunctions.ts:11:13)
    at /app/src/services/userService.ts:85:34
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
    at Query.<anonymous> (/app/src/services/userService.ts:76:89)
    at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/app/node_modules/pg/lib/client.js:312:19)
20/10/2023 12:03:02: error: uncaughtException: Cannot read properties of undefined (reading 'user_id')
TypeError: Cannot read properties of undefined (reading 'user_id')
    at parseUserToSend (/app/src/utils/commonFunctions.ts:11:13)
    at /app/src/services/userService.ts:85:34
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
    at Query.<anonymous> (/app/src/services/userService.ts:76:89)
    at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/app/node_modules/pg/lib/client.js:312:19)
20/10/2023 14:16:00: error: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:278:15)
    at /app/src/controllers/projectController.ts:199:48
    at /app/src/services/projectService.ts:256:9
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
20/10/2023 18:04:54: error: uncaughtException: migration is not a function
Error: migration is not a function
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
20/10/2023 18:08:22: error: uncaughtException: error: column "123456" does not exist
Error: error: column "123456" does not exist
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
20/10/2023 18:08:49: error: uncaughtException: error: column "123456" does not exist
Error: error: column "123456" does not exist
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
20/10/2023 18:09:05: error: uncaughtException: error: column "123456" does not exist
Error: error: column "123456" does not exist
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
20/10/2023 18:12:46: error: uncaughtException: error: syntax error at or near "NOT"
Error: error: syntax error at or near "NOT"
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
20/10/2023 18:13:01: error: uncaughtException: error: column "123456" does not exist
Error: error: column "123456" does not exist
    at /app/src/migrations/index.ts:22:13
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
21/10/2023 22:55:17: error: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:278:15)
    at /app/src/controllers/projectController.ts:201:48
    at /app/src/services/projectService.ts:256:9
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
22/10/2023 19:26:36: error: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:278:15)
    at /app/src/controllers/projectController.ts:201:48
    at /app/src/services/projectService.ts:256:9
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
23/10/2023 12:51:12: error: uncaughtException: Cannot set headers after they are sent to the client
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/app/node_modules/express/lib/response.js:278:15)
    at /app/src/controllers/projectController.ts:201:48
    at /app/src/services/projectService.ts:256:9
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
23/10/2023 19:27:00: error: uncaughtException: error: duplicate key value violates unique constraint "users_email_key"
Error: error: duplicate key value violates unique constraint "users_email_key"
    at /app/src/migrations/index.ts:22:19
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
23/10/2023 19:27:15: error: uncaughtException: error: duplicate key value violates unique constraint "users_email_key"
Error: error: duplicate key value violates unique constraint "users_email_key"
    at /app/src/migrations/index.ts:22:19
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
23/10/2023 19:39:13: error: uncaughtException: error: duplicate key value violates unique constraint "users_email_key"
Error: error: duplicate key value violates unique constraint "users_email_key"
    at /app/src/migrations/index.ts:22:19
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
23/10/2023 19:39:23: error: uncaughtException: error: duplicate key value violates unique constraint "users_email_key"
Error: error: duplicate key value violates unique constraint "users_email_key"
    at /app/src/migrations/index.ts:22:19
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
23/10/2023 20:02:26: error: uncaughtException: ⨯ Unable to compile TypeScript:
src/services/loginService.ts(31,25): error TS2322: Type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' is not assignable to type 'User'.
  Property 'user_password' is missing in type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' but required in type 'Omit<Omit<CreateReceivedUser, "confirm_password">, "birthday">'.

TSError: ⨯ Unable to compile TypeScript:
src/services/loginService.ts(31,25): error TS2322: Type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' is not assignable to type 'User'.
  Property 'user_password' is missing in type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' but required in type 'Omit<Omit<CreateReceivedUser, "confirm_password">, "birthday">'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
23/10/2023 20:02:35: error: uncaughtException: ⨯ Unable to compile TypeScript:
src/services/loginService.ts(6,31): error TS5097: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
src/services/loginService.ts(31,25): error TS2322: Type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' is not assignable to type 'User'.
  Property 'user_password' is missing in type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' but required in type 'Omit<Omit<CreateReceivedUser, "confirm_password">, "birthday">'.

TSError: ⨯ Unable to compile TypeScript:
src/services/loginService.ts(6,31): error TS5097: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
src/services/loginService.ts(31,25): error TS2322: Type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' is not assignable to type 'User'.
  Property 'user_password' is missing in type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' but required in type 'Omit<Omit<CreateReceivedUser, "confirm_password">, "birthday">'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
23/10/2023 20:02:50: error: uncaughtException: ⨯ Unable to compile TypeScript:
src/services/loginService.ts(31,25): error TS2322: Type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' is not assignable to type 'User'.
  Property 'user_password' is missing in type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' but required in type 'Omit<Omit<CreateReceivedUser, "confirm_password">, "birthday">'.

TSError: ⨯ Unable to compile TypeScript:
src/services/loginService.ts(31,25): error TS2322: Type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' is not assignable to type 'User'.
  Property 'user_password' is missing in type '{ user_id: any; full_name: any; email: any; sex: any; birthday: any; }' but required in type 'Omit<Omit<CreateReceivedUser, "confirm_password">, "birthday">'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
23/10/2023 20:03:40: error: uncaughtException: ⨯ Unable to compile TypeScript:
src/controllers/loginController.ts(42,8): error TS2345: Argument of type '(message: string) => void' is not assignable to parameter of type '(message: string | object) => void'.
  Types of parameters 'message' and 'message' are incompatible.
    Type 'string | object' is not assignable to type 'string'.
      Type 'object' is not assignable to type 'string'.

TSError: ⨯ Unable to compile TypeScript:
src/controllers/loginController.ts(42,8): error TS2345: Argument of type '(message: string) => void' is not assignable to parameter of type '(message: string | object) => void'.
  Types of parameters 'message' and 'message' are incompatible.
    Type 'string | object' is not assignable to type 'string'.
      Type 'object' is not assignable to type 'string'.

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
24/10/2023 16:28:31: error: uncaughtException: getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at /home/carlos/workspace/simple-tasks-backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
24/10/2023 16:28:31: error: uncaughtException: getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at /home/carlos/workspace/simple-tasks-backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221114103600__CreateTableUser.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221114103600__CreateTableUser.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221116101700__AddLastModifiedToMigrationTable.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221116101700__AddLastModifiedToMigrationTable.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221121084300__CreateTableProjects.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221121084300__CreateTableProjects.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221121084400__CreateTableTasks.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221121084400__CreateTableTasks.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221121085400__CreateTablePlans.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221121085400__CreateTablePlans.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221121085900__CreateTableUserPlans.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221121085900__CreateTableUserPlans.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221121092300__CreateTableSharedTasks.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221121092300__CreateTableSharedTasks.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20221121092900__InsertPlans.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20221121092900__InsertPlans.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20231016085500__AddColumnIsUserActive.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20231016085500__AddColumnIsUserActive.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:29:57: error: uncaughtException: Cannot find module './queries/T20231020150400__CreateSampleUser.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
Error: Cannot find module './queries/T20231020150400__CreateSampleUser.ts'
Require stack:
- /app/build/migrations/index.js
- /app/build/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /app/build/migrations/index.js:58:45
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at /app/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:165:16)
24/10/2023 19:38:22: error: uncaughtException: error: duplicate key value violates unique constraint "users_email_key"
Error: error: duplicate key value violates unique constraint "users_email_key"
    at /app/build/migrations/index.js:26:27
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:03:46: error: uncaughtException: error: syntax error at end of input
Error: error: syntax error at end of input
    at /app/build/migrations/index.js:26:27
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:07:29: error: uncaughtException: error: syntax error at end of input
Error: error: syntax error at end of input
    at /app/build/migrations/index.js:25:23
    at step (/app/node_modules/tslib/tslib.js:195:27)
    at Object.next (/app/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:12:17: error: uncaughtException: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
Error: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:14:31: error: uncaughtException: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
Error: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:14:31: error: uncaughtException: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
Error: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:15:27: error: uncaughtException: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
Error: getaddrinfo EAI_AGAIN dpg-cks2c305vl2c73cpdtbg-a
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:49:51: error: uncaughtException: connection is insecure (try using `sslmode=require`)
error: connection is insecure (try using `sslmode=require`)
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:55:01: error: uncaughtException: permission denied for schema public
error: permission denied for schema public
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 12:58:51: error: uncaughtException: permission denied for schema public
error: permission denied for schema public
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
25/10/2023 13:01:49: error: uncaughtException: permission denied for schema public
error: permission denied for schema public
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
